apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
  namespace: default
  labels:
    app: my-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
      - name: my-go-app
        image: "docker.io/reem123/my-go-app:hash"
        ports:
        - containerPort: 8080
