apiVersion: v1
kind: Service
metadata:
  name: my-go-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: my-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
